export const flightData = [
  {
    route: { from: "JFK", to: "LAX" },
    flights: [
      {
        airline: "Delta",
        price: 300,
        duration: "6h",
        stops: ["ORD"],
        departureTime: "08:00 AM",
        arrivalTime: "02:00 PM",
        aircraft: "Boeing 737",
        availableSeats: 20,
      },
      {
        airline: "American Airlines",
        price: 350,
        duration: "6.5h",
        stops: [],
        departureTime: "09:30 AM",
        arrivalTime: "04:00 PM",
        aircraft: "Airbus A320",
        availableSeats: 15,
      },
    ],
  },
  {
    route: { from: "JFK", to: "ORD" },
    flights: [
      {
        airline: "United",
        price: 150,
        duration: "2.5h",
        stops: [],
        departureTime: "06:00 AM",
        arrivalTime: "08:30 AM",
        aircraft: "Boeing 757",
        availableSeats: 30,
      },
      {
        airline: "Delta",
        price: 200,
        duration: "3h",
        stops: [],
        departureTime: "10:00 AM",
        arrivalTime: "01:00 PM",
        aircraft: "Boeing 737",
        availableSeats: 25,
      },
    ],
  },
  {
    route: { from: "LAX", to: "ORD" },
    flights: [
      {
        airline: "Southwest",
        price: 200,
        duration: "4h",
        stops: ["DEN"],
        departureTime: "11:00 AM",
        arrivalTime: "03:00 PM",
        aircraft: "Boeing 737",
        availableSeats: 10,
      },
      {
        airline: "Delta",
        price: 250,
        duration: "4.5h",
        stops: [],
        departureTime: "03:00 PM",
        arrivalTime: "07:30 PM",
        aircraft: "Airbus A321",
        availableSeats: 5,
      },
    ],
  },
  {
    route: { from: "SFO", to: "JFK" },
    flights: [
      {
        airline: "JetBlue",
        price: 400,
        duration: "5.5h",
        stops: [],
        departureTime: "07:00 AM",
        arrivalTime: "12:30 PM",
        aircraft: "Airbus A320",
        availableSeats: 40,
      },
      {
        airline: "American Airlines",
        price: 450,
        duration: "6h",
        stops: ["DEN"],
        departureTime: "01:00 PM",
        arrivalTime: "07:00 PM",
        aircraft: "Boeing 777",
        availableSeats: 18,
      },
    ],
  },
  {
    route: { from: "ORD", to: "ATL" },
    flights: [
      {
        airline: "Delta",
        price: 180,
        duration: "2h",
        stops: [],
        departureTime: "09:00 AM",
        arrivalTime: "11:00 AM",
        aircraft: "Boeing 737",
        availableSeats: 22,
      },
      {
        airline: "Southwest",
        price: 150,
        duration: "2.5h",
        stops: ["STL"],
        departureTime: "01:00 PM",
        arrivalTime: "03:30 PM",
        aircraft: "Boeing 737 MAX",
        availableSeats: 8,
      },
    ],
  },
  {
    route: { from: "ATL", to: "LAX" },
    flights: [
      {
        airline: "United",
        price: 320,
        duration: "4.5h",
        stops: [],
        departureTime: "02:00 PM",
        arrivalTime: "06:30 PM",
        aircraft: "Airbus A320",
        availableSeats: 12,
      },
      {
        airline: "Spirit Airlines",
        price: 200,
        duration: "5h",
        stops: ["DFW"],
        departureTime: "08:00 AM",
        arrivalTime: "01:00 PM",
        aircraft: "Airbus A319",
        availableSeats: 50,
      },
    ],
  },
];
